### ISSUE TITLE
Game crash when tapping space at world creation

### ISSUE THREAD

**Issue by ThunderSphun** [MSandro/sky_fabrication3#1]
[crash report](https://github.com/MSandro/sky_fabrication3/files/9079463/crash-2022-07-10_18.48.38-client.txt)
probably caused by some key configured to space, but only jump uses space in my profile

**Comment by MSandro** [comment]
rellated to:
https://github.com/LukeGrahamLandryMC/travel_anchors/issues/4

**Comment by MSandro** [comment]
I will remove the mod in v0.3 to solve the issue.

**Comment by MSandro** [comment]
the mod will be added in a future version, the issue was fixed.
