### ISSUE TITLE
Vanishing items from player inventory

### ISSUE THREAD

**Issue by alpha-pvp** [MSandro/sky_fabrication3#10]
If I transfer items from a chest etc. into my inventory some just vanish when I close the chest. It doesn't seem to be item specific though it can happen to anything. Some seem to reappear after a while. I can't seem to force the issue it appears randomly.

**Comment by MSandro** [comment]
Could u try to remove the Inventorio Mod and tell me if the issue still appears?

**Comment by alpha-pvp** [comment]
I removed the mod, but now this happens (video). I don't know if this is something new or still the same issue.

https://user-images.githubusercontent.com/96375968/182024057-c0286524-a11b-49e3-95df-6e6bb05d0ed4.mp4

**Comment by MSandro** [comment]
> I removed the mod, but now this happens (video). I don't know if this is something new or still the same issue.

I am testing a lot to figure out what is going wrong here. So, removing Inventorio seems to cause more issues.
In my current 0.4 test environment I updated many mods which seems to have fixed it. But I'll leave the issue open, please let me know if there are still these problems after the update to 0.4 which will be released today.

**Comment by alpha-pvp** [comment]
It seems, that the upgrade has fixed the issue, thanks.
