### ISSUE TITLE
@Suggestion Use EMI rather than REI as EMI is better in my opinion.

### ISSUE THREAD

**Issue by RoboXGamer** [MSandro/sky_fabrication3#11]
@Suggestion

Use EMI rather than REI as EMI is better in my opinion.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/183347366-8ce0edce-e2a4-404c-85c8-8395fb2f1160.png)
not possible, some mods are requiring REI.
and many mods did not implement EMI so they are not showing their recipes in EMI.
