### ISSUE TITLE
[Question] How can i obtain Rainbow rose

### ISSUE THREAD

**Issue by DmitryProskurin** [MSandro/sky_fabrication3#112]
I've try to progress via Spectrum quests. I stuck at Shimmerstone gem(Obtain via extractinator), i've create extractinator, but can't obtain rainbow petal, beacause it's crafted from Rainbow rose.

**Comment by DmitryProskurin** [comment]
@KonSola5, can you help me with that?

**Comment by KonSola5** [comment]
Bonemeal Grass Blocks - all flowers (apart from Botania functional flowers) can spawn in any biome thanks to a mod.

You just need a bit of luck, so prepare a bit of bonemeal or make an automated farm.

**Comment by DmitryProskurin** [comment]
@KonSola5, thanks! I've test it in another world - Rainbow rose spawn after 10 bonemeal.

Thank you for that modpack!

**Comment by KonSola5** [comment]
This modpack is made by MSandro, not me.
