### ISSUE TITLE
Lumberjack ability enables wood duplication

### ISSUE THREAD

**Issue by walkernel** [MSandro/sky_fabrication3#12]
The extra +2 plank bonus lumberjack gets from crafting logs to planks is  also applied to the result of crafting two slabs together into a plank, enabling you to craft
 
2 slabs -> 3 (1 regular + 2 bonus)  planks -> 6 slabs -> 9 planks e.t.c. 

This also seems to only happen on vanilla crafting table.

**Comment by MSandro** [comment]
thanks.
will be fixed in the next version.

**Comment by MSandro** [comment]
fixed in SF3 v0.5
