### ISSUE TITLE
Witch Water barrel bug

### ISSUE THREAD

**Issue by dis0x** [MSandro/sky_fabrication3#15]
When making witchwater with a barrel on top of mycelium the barrel, the witchwater disappear before I can bucket it out.
A tiny amount of witchwater looks to be left in the barrel so it needs to be broken and placed again to work again.

It's been reported to the Fabricae Ex Nihilo issue tracker
See https://github.com/LordDeatHunter/FabricaeExNihilo/issues/16

There is a PR already in the work to fix it, hopefully it gets merged soon

Edit: Just realized you're the one that opened that issue, my bad. Should I close this?

**Comment by MSandro** [comment]
Its fine, I will keep this opened until its fixed in the modpack.

**Comment by MSandro** [comment]
fixed in SF3 v0.5
