### ISSUE TITLE
Free Enchanted Books Off The Grindstone

### ISSUE THREAD

**Issue by CarbyDood** [MSandro/sky_fabrication3#16]
Usually, when you place an enchanted tool or armor along with a book on the grindstone, you can transfer the enchantments from the tool to the book at the cost of the appropiate amount of levels. If you do not have enough levels, you will instead just grind the enchantments off the tool and get some XP back. I assume this is the intended behavoir, however when the latter occurs and you just grind the enchantments off the tool or armor because you don't have enough levels, the book becomes enchanted with the tool's enchantments at no XP cost at all. I assume this is *not* the intended behavoir. Link to video of the bug: https://youtu.be/NG2oEOF-hXw

**Comment by MSandro** [comment]
fixed in SF3 v0.5
