### ISSUE TITLE
Died in Nether and cannot open inventory and permenently slowed with an incressed hunger rate

### ISSUE THREAD

**Issue by anima7x7** [MSandro/sky_fabrication3#17]
Died in Nether and cannot open inventory and permenently slowed with an incressed hunger rate
I'm on a Lan server

![image](https://user-images.githubusercontent.com/111623360/185727464-841e7738-7006-4ae6-be96-145aca9db0b7.png)

**Comment by anima7x7** [comment]
It's like thers somthing in my first inventory slot and I cannot scroll off of it.

![image](https://user-images.githubusercontent.com/111623360/185727561-48c18b29-635d-4abe-8752-210d97c9912a.png)

**Comment by anima7x7** [comment]
FIXED IT!!!!!!!!!!!!!!!!!!!!!

When I died with something in my inventory it created 2 graves. One with the stuff I lost when I died in the nether and the other with all the milk buckets I'd been thrown. Picking the first one up fixed the issue and picking the seconed one up just gave me the milk buckets.

![image](https://user-images.githubusercontent.com/111623360/185727661-cef20b7e-7d8c-43fb-8291-99e6590a9c69.png)

**Comment by MSandro** [comment]
> FIXED IT!!!!!!!!!!!!!!!!!!!!!
> When I died with something in my inventory it created 2 graves. One with the stuff I lost when I died in the nether and the other with all the milk buckets I'd been thrown. Picking the first one up fixed the issue and picking the seconed one up just gave me the milk buckets.

2 graves? wtf, this is strange, I will try to reproduce some of your problems to enhance the behaviour.

**Comment by MSandro** [comment]
this issue is very hard for me to reproduce, did you noticed this bug again?

**Comment by MSandro** [comment]
closed due to no response.
