### ISSUE TITLE
Botania Flower Generation

### ISSUE THREAD

**Issue by micolas91** [MSandro/sky_fabrication3#2]
Hi, when using bonemeal on grass it generated grass, flowers, Botania flowers but also Botania functional flowers. I got an Orechid, Daffomill, Tangleberrie and a Pure Daisy with two bonemeal. I don't believe this is intentional as it would cause a huge early game skip.

**Comment by micolas91** [comment]
Added note, unable to complete Botania Questline's second quest "Find Mystical Flowers". Even going into creative to spawn the specific tall flower displayed in quest image doesn't result in completion.

**Comment by MSandro** [comment]
solved in v0.3
release is planed for tomorrow.
