### ISSUE TITLE
Andesite in Millstone creates cobblestone

### ISSUE THREAD

**Issue by NightUndead** [MSandro/sky_fabrication3#23]
My REI says that the Millstone can be used to create Crushed Andesite from Andesite, but it conflicts with another recipe in the Millstone which creates cobblestone from Andesite.
![image](https://user-images.githubusercontent.com/85498199/189491870-3370a457-ee2a-4528-ad67-e2d03cf8f48b.png)
As a result, personally I get cobblestone whenever I mill Andesite instead of the desired Crushed Andesite.

**Comment by NightUndead** [comment]
I've now gotten access to the Crushing Wheels and I have the same issue there.

In addition Granite also has conflicting recipes (Red Sand and Crushed Granite).

**Comment by MSandro** [comment]
I will fix it in the next version

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/189602028-733b721d-2e83-4f3a-8c6f-b45899ef873d.png)
fixed in the Dev-Environ

**Comment by MSandro** [comment]
fixed in 0.5.1
