### ISSUE TITLE
New Single Player world bugged [0.5.1]

### ISSUE THREAD

**Issue by iamshift** [MSandro/sky_fabrication3#24]
Creating a new single player world with Sky Block as the world type is creating a Sky Grid instead.

Workaround: create the world with server and copy it to the client.

**Comment by MSandro** [comment]
I have tried to reproduce this issue.
if I just create a new world without changing the Type, it generates the Sky Block World.

did you added or removed a mod? I am using FancyMenu to set the default World-Type, if the selection of the Types changes, it will fail.

**Comment by iamshift** [comment]
I did some more testing and found the culprit, game rules. 
If you open the game rules window and then create the world it defaults to Sky Grid. 

Idk if it's a issue with the modpack or with Fancy Menu Mod itself.

**Comment by MSandro** [comment]
ok thanks, I can confirm this issue.
same if I return from the DataPack Screen.
might be a issue with FancyMenu, I will continue testing and try to fix the issue by my own or if needed with help from the FancyMenu Dev.

**Comment by MSandro** [comment]
not able to fix, because of FancyMenu
