### ISSUE TITLE
Gravel quest wouldn't complete

### ISSUE THREAD

**Issue by wickedsharp** [MSandro/sky_fabrication3#26]
The gravel quest (after the stone hammer quest) wouldn't complete. I made a number of gravel using both wood and stone hammers, before and after accessing the quest, but it never triggered. Had to use cheats to trigger it.

**Comment by MSandro** [comment]
I will try to fix this, but it is very randomly that FTB Quests does not detect some tasks.
Often it could be fixed by putting all (in this case) gravel in a chest, and put it back in your inventory.

**Comment by MSandro** [comment]
(hopefully) fixed in v0.5.2
