### ISSUE TITLE
No obvious way to obtain Sulfur

### ISSUE THREAD

**Issue by Moe801** [MSandro/sky_fabrication3#27]
Maybe I am missing something but at this point, I don't see a way to get the sulfur needed for advancing into the electrical age.

I need to craft Rubber Sheets. Therefore I need synthetic Rubber and paper in the Modern Industrialization Mixer. To get synthetic Rubber I need to mix synthetic oil with Sulfur. I don't see a way to get sulfur without advancing into the electrical age and don't know a way to advance into the electrical age without sulfur.

Version 0.5.1

**Comment by Moe801** [comment]
Did not see the synthetic oil craft

**Comment by chezpaul** [comment]
I'm in the same boat as you. What did you do?
