### ISSUE TITLE
Various issues I find during my playthrough

### ISSUE THREAD

**Issue by Lancelotbronner** [MSandro/sky_fabrication3#29]
In the `Barrel of fun quest`, it only accepts an oak barrel but bamboo island starts could get other types of wood, I think it should accept any wooden barrel.

Love the modpack so far, just what I've been looking for!

**Comment by Lancelotbronner** [comment]
Quest `A Dirt-y idea` doesn't recognize I have the kelp sporophyte and sugarcane seeds. (I got them from sieving sand in a waterlogged copper mesh)

Really enjoying this pack!

**Comment by Lancelotbronner** [comment]
Some config changes I had to make, not necessarily an issue but just to let you know of some of the dead times in the pack.

- Crop dusting should have a slightly higher chance because currently I could be twerking for minutes without anything happening
- I reduced ultimine's hunger requirements a bit because destroying a tree's leaves would take out pretty much my whole hunger bar (I'm a shulker which maybe doesn't help)
- I increased ultimine's block limit to destroy whole trees

**Comment by Lancelotbronner** [comment]
I saw some playthroughs that used witch water instead of water in cobblegens to also provide andesite, granite and diorite but that doesn't seem to work, is that intended?

**Comment by MSandro** [comment]
thanks for reporting this issue. I will go through all of them and will try to fix them in the next update.

Using Witchwater and Lava in a "Cobblestone-Generator" Setup works fine for me. It should work, its a intended feature from Ex-Nihilo.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/195395277-ffbeb549-03aa-440d-8138-0cda6cfbfdb7.png)
I've placed the granite and cobblestone under the fluid to disable my generator, but once I remove them, it start producing the blocks, tested in 0.5.2

**Comment by MSandro** [comment]
Barrel of fun quest: will be fixed in 0.5.3
A Dirt-y idea quest: this issue can happen for any quest is a issue in FTB Quests
I will set the hunger for Ultimine to 100.
The max_blocks will be set to 128 in the next update.
Crop Dusting chance will be set to 12.

thanks for your feedback.

**Comment by MSandro** [comment]
fixed in 0.5.3
