### ISSUE TITLE
Furnace Slabs by improved stations - nonfunctional

### ISSUE THREAD

**Issue by micolas91** [MSandro/sky_fabrication3#3]
Furnace Slabs  from the "improved stations" mod can be crafted and placed without issue but don't function. Broken and replaced and issue still persists. Regular furnaces function fine. Items can be place inside the Furnace Slab but cooking process doesn't take place. No consumption of fuel items either.

**Comment by MSandro** [comment]
Known Bug, I will remove the recipes for them.
https://github.com/shedaniel/improved-stations/issues/33
