### ISSUE TITLE
trinkets are broken [0.5.3]

### ISSUE THREAD

**Issue by xAphex** [MSandro/sky_fabrication3#31]
trinkets dont work, when i hover over armor slots it's supposed to show the trinket slots.

reading online i found out that the mod **Charm** is what is breaking **Trinkets** mod.

the fix they implemented was to remove the mod **Charm** altogether, but idk if this ruins the gameplay.

hope you can fix this problem, thank you ❤️

**Comment by MSandro** [comment]
there is currently no update for Charm. The Mod offers a few improvements and tweaks to the game, removing it would not ruin the gameplay.
can you give a example which trinket is broken?
I can not understand why charm should cause the problem, it has no support for Trinkets as far as I know.

**Comment by MSandro** [comment]
I am still not able to replicate this issue in the current dev-environment

**Comment by MSandro** [comment]
hopefully fixed in 0.5.4
