### ISSUE TITLE
Realistic Sleep cause several issues

### ISSUE THREAD

**Issue by MSandro** [MSandro/sky_fabrication3#32]
Moon Phases, Enhanced Celestials, and Seasons are broken because of this mod.
https://github.com/Steveplays28/realisticsleep/issues/5

**Comment by MSandro** [comment]
will be removed in 0.5.4

**Comment by Eartelyna** [comment]
Apparently the issue is fixed in the version 1.6.0 of the mod

**Comment by MSandro** [comment]
thanks I have updated the mod in v0.5.4 it seems to solve the issues.
