### ISSUE TITLE
Unable to Obtain Raw Gold Piece from Sieving (0.5.4)

### ISSUE THREAD

**Issue by hayandrews** [MSandro/sky_fabrication3#37]
In both a two player server and a single world we were unable to obtain raw gold pieces through sieves which we should obtain through the Fabricae Ex Nihilo mod using the proper meshes (iron on up) with gravel. We tested just the mod with the version the mod pack is using and was able to produce gold so there may be an impact with the other mods in the pack preventing this. Attempting to click the raw gold piece when searching will not bring up a method to obtain it either.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/201498111-8223769a-d943-45ec-a173-d5cf31b9bd9c.png)
intended, produce Gold with Create

**Comment by hayandrews** [comment]
Thank you, glad to know it's not an issue!
