### ISSUE TITLE
Zinc ingot in mechanical press crashes the server [0.5.2+0.5.5]

### ISSUE THREAD

**Issue by hleskien** [MSandro/sky_fabrication3#38]
Hi,

when I try to press a Tech Reborn Zinc Ingot in a Create Mechanical Press the server crashes instantly.
Versions 0.5.2 and 0.5.5

Kind regards

Holger

[crash-2022-11-15_20.05.52-server.txt](https://github.com/MSandro/sky_fabrication3/files/10015909/crash-2022-11-15_20.05.52-server.txt)

**Comment by MSandro** [comment]
Thanks for reporting this, I can confirm this issue and have reported it on the Github Repo of the Create-Fabric project.
https://github.com/Fabricators-of-Create/Create/issues/592

**Comment by MSandro** [comment]
fixed in dev-environment

**Comment by MSandro** [comment]
will be fixed in 0.5.6a

**Comment by hleskien** [comment]
Thank you!
