### ISSUE TITLE
Prismarine Shard / REI recipe display

### ISSUE THREAD

**Issue by micolas91** [MSandro/sky_fabrication3#4]
When using REI, if you click on the Prismarine Shard and go to the "Sifting" tab for FabricaeExnihilo mod it shows a 40% drop rate from gravel when using a waterlogged sieve for either a flint or iron mesh. When you check the uses for gravel (u key) and go to the same tab, both the flint or iron mesh with a waterlogged sieve show a 1% drop rate. (likely the 40% rate is in error as they do not drop often)

**update: issue affects multiple recipes. Confirmed differences in several recipes with % drop rate differences between searching for item dropped vs item that produces it.

**Comment by MSandro** [comment]
already reported to the Mod Developer:
https://github.com/LordDeatHunter/FabricaeExNihilo/issues/18

**Comment by MSandro** [comment]
fixed in SF3 v0.5
