### ISSUE TITLE
Crash when producing Zinc plate

### ISSUE THREAD

**Issue by RedReaperLp** [MSandro/sky_fabrication3#41]
When i am trying to proccess zinc ingots to zinc plates with create, the server crashes in the moment the thing stamps
[crash-2022-11-23_15.07.43-server.txt](https://github.com/MSandro/sky_fabrication3/files/10076768/crash-2022-11-23_15.07.43-server.txt)

**Comment by MSandro** [comment]
duplicate of #38
I am working on it.
