### ISSUE TITLE
Recipe for fluid trashcan extremely late game

### ISSUE THREAD

**Issue by twothe** [MSandro/sky_fabrication3#42]
I assume that a fluid trashcan is nothing too powerful and can/should be allowed early in the game. However the current recipe requires Aluminum bars, which are not available until very late in the game, forcing the player to deal with fluid excess in very complicated ways.

**Comment by MSandro** [comment]
Aluminum is Mid-Game (late Steam Age)
but you have the option to use a Entangled Tank with a Trash Can in the Crafting table to get a Fluid Trash Can.
![image](https://user-images.githubusercontent.com/10937159/203788007-1f94fbca-e430-4aa8-b385-513540ceee52.png)
