### ISSUE TITLE
fluid FabricAeExnihil blood recipe not working [0.55]

### ISSUE THREAD

**Issue by Syclone81** [MSandro/sky_fabrication3#43]
i try some ways to get the right blood (fabricAeExnihilo.blood).
the way over smeltery is broken and gives me always hephaestus blood.

with this blood, i miss this recipes that combinate witchwater with blood and also missing red sand. for this recipe you need to get FabricaeExNihilo.blood

i do not know other ways to get blood. then only over a smeltery to fill it into a bucked or a tank.
![bucket_from_smeltery](https://user-images.githubusercontent.com/12032759/203688218-3ed81353-bb0d-421c-9419-14a1eec97d4d.jpg)
![Coagulated_Blood](https://user-images.githubusercontent.com/12032759/203688232-aeed0af6-7fac-4673-a2be-feee9801e86f.jpg)
![fabricaeexnihilo_blood](https://user-images.githubusercontent.com/12032759/203688240-e6ae8388-af08-436b-9272-4ee786969486.jpg)
![smeltery_blood](https://user-images.githubusercontent.com/12032759/203688244-15513397-5374-42a3-b674-418792c9ace3.jpg)

is this a bug or is there a way i never know ?
when you have a way for it. a quest would be nice, to get new players better into this modpack.

thanks for your work

green marked is the fabricAeExnihilo.blood bucked
red marked is the hephaestus.blood bucked
![Unbenannt](https://user-images.githubusercontent.com/12032759/203688530-99156cb6-8c36-469f-a138-db2cfca10363.PNG)

**Comment by Syclone81** [comment]
my version is [0.5.5]

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/203787332-9c620d48-be8b-4c04-905b-72ba0c616db5.png)
Please read the instructions in the Quest-Book.
You have to enchant a barrel with Thorns. If a player or a Mob stands on the placed enchanted barrel it will deal damage and collect blood!

**Comment by Syclone81** [comment]
ah ok, that make sense. thanks alot
