### ISSUE TITLE
Messingbarren

### ISSUE THREAD

**Issue by 3rdnukk3l** [MSandro/sky_fabrication3#44]
Das Rezept für die Messingbarren passt nicht mit dem zusammen, was man wirklich machen muss.
Laut Rezept soll mann 1x Kupfer + 1x Zink im Mixer bei "wenig Hitze" mixen.
Tatsächlich habe ich es im Creator-Mode nur mit "extremer Hitze" durch einen gefeuerten Lohenbrenner hinbekommen. Soll das wirklich so?!
Wäre für das erste Messing ein ziemlich teures Rezept!!

**Comment by MSandro** [comment]
Danke fürs einsenden dieses Issues.
Ich werde das Prüfen, es scheint mir aber ein Fehler direkt im Create Mod zu sein.
