### ISSUE TITLE
Crashing because of Croparia

### ISSUE THREAD

**Issue by RedReaperLp** [MSandro/sky_fabrication3#47]
[crash-2022-11-27_19.12.04-server.txt](https://github.com/MSandro/sky_fabrication3/files/10105243/crash-2022-11-27_19.12.04-server.txt)

**Comment by MSandro** [comment]
https://github.com/Dalarion/Croparia/issues/22

**Comment by MSandro** [comment]
disabled Greenhouses temporarily
