### ISSUE TITLE
crash loop on my world thanks to applied botanics

### ISSUE THREAD

**Issue by Uchiwars** [MSandro/sky_fabrication3#48]
https://crashy.net/eDrAFt0a45Jaw1VpBNhz

ok i added an export bus to the mana pool in question
configured to export mana from my system (i managed to filter it thanks to the memory card which works on others buses too)
and now my game is in a crash loop
can't open my world
and i don't think there is a backup mod in this modpack...

**Comment by ramidzkh** [comment]
Sorry for not seeing the issue earlier, but I'd recommend removing Applied Botanics from your mods list for now. I have started looking for a fix
