### ISSUE TITLE
With the newest version the Server crashes, before even starting completely

### ISSUE THREAD

**Issue by RedReaperLp** [MSandro/sky_fabrication3#50]
[latest.log](https://github.com/MSandro/sky_fabrication3/files/10126688/latest.log)

**Comment by MSandro** [comment]
Hello, i will upload a fixed file tomorrow.

**Comment by MSandro** [comment]
But please maybe try to install a new server instance, the log doesn't make mich sense to me.
I have tested the server file today without any problems.

Maybe some additional informations might be helpful (OS and Java Version)

**Comment by RedReaperLp** [comment]
Linux v32806 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64

I tried it with a new instance, but this also doesnt work

**Comment by MSandro** [comment]
thanks, did you add any additional mod or changed any config for your instance?

**Comment by MSandro** [comment]
I am still not able to reproduce the issue.
But here is my Packwiz Installer-Script:
https://raw.githubusercontent.com/MSandro/sky_fabrication3/main/0.5.6_server_installer.zip
once downloaded and extracted, you should be able to run the install_and_update.sh file.
it will download all files and after its done, you can execute the start.sh file.

I hope this method works for you.

**Comment by RedReaperLp** [comment]
Okay, that works now fine, but the World can´t be open anyways, what i expected, was that the Server will automatically remove those block, which doesnt exists but thats not the case, now without croparia, but with bewitchment:garlic
[latest.log](https://github.com/MSandro/sky_fabrication3/files/10133795/latest.log)

**Comment by MSandro** [comment]
could you upload your map somwhere as a ZIP file, I will try to repair it.
