### ISSUE TITLE
wraith-harvestscythes-2.5.3+mc1.18.2.jar in 0.5.6a server pack

### ISSUE THREAD

**Issue by mentat149** [MSandro/sky_fabrication3#53]
In case anyone else comes across this, wraith-harvestscythes-2.5.3+mc1.18.2.jar is still included in the 0.5.6a_server zip file, causing login issues. Deleting it fixes the issue.

**Comment by MSandro** [comment]
will be fixed in 0.5.6a-hotfix1:
![image](https://user-images.githubusercontent.com/10937159/206296835-e6f250e0-96d6-4d2b-872d-10df5e20d7eb.png)

**Comment by MSandro** [comment]
the new file will be available soon:
https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3/files/4143785
