### ISSUE TITLE
Crashed while trying to exit inventory

### ISSUE THREAD

**Issue by VeggeieDude** [MSandro/sky_fabrication3#54]
I just started the pack and about 2 minutes in, after opening up the inventory hud for the first time, i clicked "ESC" to exit it and the game got locked.

The log says something about the Twilight Forest guide and other stuff

[2022-12-10-1.log](https://github.com/MSandro/sky_fabrication3/files/10199414/2022-12-10-1.log)

**Comment by VeggeieDude** [comment]
Oh I actually found out what causes it to crash. Trying to open the Quests hud from the Inventory screen causes the game to completely freeze.

**Comment by MSandro** [comment]
which version are you playing? if in your title screen the version number in the bottom left shows v0.5.7, please downgrade to v0.5.6a
There are many mod related issues due to several updateds I did in this update.
That's why I removed the update again.

**Comment by MSandro** [comment]
v0.5.7a is out and hopefully fixes this issue, feel free to re open the issue if you still have the issue.
