### ISSUE TITLE
[0.5.6a] @applied energistics 2 | ME System

### ISSUE THREAD

**Issue by Syclone81** [MSandro/sky_fabrication3#56]
problem: i see / find no way to get Sky Stone Dust or Sky Stone. i also play since 0.5.5 there was also no way to get Sky Stone or *dust. (i'm not deep into all this modpacks or Skyblock modpacks. YT helps alot. but not for this problem)

then in Questbook

![questbook](https://user-images.githubusercontent.com/12032759/207729687-a7f51627-41d2-4366-9614-04950d09a1e2.PNG)

this is still looked and i have no glue, what i need to do to unlock this middle quest called "Storage and Transport"

thanks for your time ;)

**Comment by Syclone81** [comment]
ah, why is Sky Stone needed ?

ME Controller need Sky Stone. no controller. less ME channels. thats my problem

**Comment by MSandro** [comment]
you can obtain Sky Stone in the Sky Islands Dimension, there are Meteors to find.
Sky Stone dust can be easy produced in several machines.
![image](https://user-images.githubusercontent.com/10937159/207782543-0c9ca0a1-5b41-49a6-87c6-6a00b5d4b2a7.png)

**Comment by Syclone81** [comment]
ok thanks, i only visit nether and overworld. but i have my ME system running :D

**Comment by MSandro** [comment]
how? Sky Stone should be just available in the Sky Islands Dimension.
