### ISSUE TITLE
Crashing because of Steam Engines and Tanks Multiblock (V.0.5.6a)

### ISSUE THREAD

**Issue by RedReaperLp** [MSandro/sky_fabrication3#59]
[crash-2022-12-10_19.07.28-server.txt](https://github.com/MSandro/sky_fabrication3/files/10272036/crash-2022-12-10_19.07.28-server.txt)

**Comment by lord-aaron-rutherfort** [comment]
the same problem with water pump / tank multiblock (create).
[crash-2022-12-28_20.05.07-server.txt](https://github.com/MSandro/sky_fabrication3/files/10319280/crash-2022-12-28_20.05.07-server.txt)

**Comment by MSandro** [comment]
please make sure to downgrade to v0.5.6a
if you are using the MultiMC Auto-Updating instance, it should downgrade automatically at the next launch.
