### ISSUE TITLE
Iron Furnace using fuel when coal is in both slots

### ISSUE THREAD

**Issue by CookieGD** [MSandro/sky_fabrication3#6]
When you put coal in both input slots of an Iron Furnace (Tech Reborn) then the fuel gets used, but because coal has no smelting recipe the top coal stays in the furnace.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/180278123-a196d127-fc2d-46a3-9ef9-693c3c2bdd94.png)
fixed in the upcomming v0.3 release
