### ISSUE TITLE
Pickaxes don't work

### ISSUE THREAD

**Issue by ximaaaaa** [MSandro/sky_fabrication3#60]
Hi, not sure if it was intended but i can't mine any stones, diorite or even a furnace with any kind of pickaxes... 
I'm using the 0.5.7 version of the modpack.

![pickaxe_issue](https://user-images.githubusercontent.com/106284337/209020552-7303589e-ce34-45c8-b70f-4d0e3c2b0529.png)

**Comment by luke98715** [comment]
Pickaxes are not working for me either

**Comment by Dan1647** [comment]
I can't use the pick either

**Comment by MSandro** [comment]
if you have tried v0.5.7, please downgrade to v0.5.6a
