### ISSUE TITLE
crash and i can't play on my map

### ISSUE THREAD

**Issue by teteos** [MSandro/sky_fabrication3#64]
hello, i have a probleme with my save..
i have crash with message
The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Amount may not be negative, but it is: -1
i can join my save but i instantely crash
can you help me ?

**Comment by MSandro** [comment]
please send the complete crash report.

**Comment by teteos** [comment]
[crash-2023-01-05_22.32.11-server.txt](https://github.com/MSandro/sky_fabrication3/files/10355786/crash-2023-01-05_22.32.11-server.txt)

**Comment by teteos** [comment]
Hello, do you have any news for me?

**Comment by MSandro** [comment]
It seems to be a problem with the Modern Dynamics pipes, I've shared the crash log in their issues.
What was the last thing you connected with those pipes?

**Comment by teteos** [comment]
i have connecte a fluid pipe(modern-dynamics) at my water pump (create)

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/212725434-c3751bd0-7e36-4bb8-a952-26f45b6e4d8f.png)
interesting, I am not able to reproduce the issue, my pipe is getting filled up.

**Comment by MSandro** [comment]
I would suggest you to reinstall the modpack with v0.5.7a and try to load up your broken world.
there was a broken modpack version v0.5.7 which I have deleted, maybe you have installed this version and the update to v0.5.7a did not work correctly.

**Comment by MSandro** [comment]
closed because of no response since weeks.
