### ISSUE TITLE
I can't fly with glitch armor

### ISSUE THREAD

**Issue by Dan1647** [MSandro/sky_fabrication3#66]
![imagen_2023-01-09_231111755](https://user-images.githubusercontent.com/121525932/211467047-3b204246-4ffb-47e5-9f16-71926b63696a.png)

**Comment by MSandro** [comment]
thanks I will check it out.

**Comment by MSandro** [comment]
will be fixed in 0.6.0
![image](https://user-images.githubusercontent.com/10937159/222396708-85a09261-8a55-40f4-94de-d8d0184722db.png)

**Comment by KonSola5** [comment]
Woah, this mod's flight bar has been broken since 1.17... And still unfixed. 🤷‍♂️
