### ISSUE TITLE
Wither eats/breaks Witherproof Blocks

### ISSUE THREAD

**Issue by ImperialSky** [MSandro/sky_fabrication3#70]
Have a Problem. The Witherproof Blocks/Glass von Kibe and The Wither Proof Obsidian from Industrial Revolution arent stoping it from eating through but i noticed that it only happens when i damage it.

Modpack Version: 0.5.6a (Curse Forge)

P.S.: First time posting an issue. If more Infomation is needed please tell me.

**Comment by Silky777** [comment]
This happens, if I understand correctly, due to the Progressive Bosses "charge" attack the wither has. This explosion pretty much renders most forms of wither proof block useless, because it isn't coded like a normal wither explosion.

**Comment by MSandro** [comment]
Thanks for reporting.
I will try to disable this feature from progressive bosses.

**Comment by MSandro** [comment]
Progressive Bosses will be removed in SF3 v0.6.0.
this seems to fix the issue.
