### ISSUE TITLE
Sky Islands issues, and lots of them

### ISSUE THREAD

**Issue by Silky777** [MSandro/sky_fabrication3#72]
1. 80% of sea monuments are completely unbeatable due to the fact that you're prevented from breaking blocks while within their range while the Elder Guardians are alive, but most of them generate in a way where you can't even get inside to kill the Elder Guardians.

2. Deserts don't seem to spawn, correct me if I'm wrong, which means that the Old Eye from End Remastered is unobtainable. (this makes the grind for the End Remastered eyes even more nightmarish).

3. Buried treasure doesn't generate most of the time due to it usually ending up in a spot where it would spawn in midair, meaning that it simply won't spawn at all.

**Comment by Silky777** [comment]
4. The villages there don't count as villages according to the game, making raids impossible. Which makes finding a Woodland Mansion the only possible way to get an Evoker, making another one of the End Remastered eyes nigh unobtainable.

**Comment by KonSola5** [comment]
5. Ancient Ruins from Spectrum do not spawn at all, it makes Jade Vine Bulbs (necessary for Infinity Catalysts), Blood Orchids and Amaranth Grains completely unobtainable. This locks you from a bit of Spectrum side content, including ability to craft Budding Onyx (Try using /locate spectrum:ancient_ruins, it fails.)

For the raid issue - bring a villager to the overworld using Kibe's Diamond lasso and place a bed near it. 1 villager and 1 bed is enough for a village, which means you can summon a raid.

Edit: Deserts do spawn, however, they are very rare (this one with a pyramid is 5k blocks away from home portal in my world)
![2023-02-10_21 09 05](https://user-images.githubusercontent.com/125081901/218188642-defd39e5-434a-44cb-9ce8-15028013e15b.png)

**Comment by KonSola5** [comment]
A fix to Ancient Ruins spawning will appear in the pull request. For some reason, MSandro decided to set the spacing to 64 (aka the structure tries to spawn once in 1024 blocks).

Changed height ranges to Y: [10, 96], spacing to 25 (once in 400 blocks, much more reasonable) and separation of 10. Also spawns the Color Combinations and Wireless Redstone rooms, so it will fix point 5 above.

Anyways, you can view the above argument with Spectrum's developer ;D

**Comment by MSandro** [comment]
I have fixed the Raid Problem (4.) in my Dev Environment,  SF3 v0.6.0 will be released soon.

**Comment by MSandro** [comment]
I think 2. can be fixed by improving the /kubejs/data/sf3/worldgen/noise_settings/void_noise.json file.
the other points should be solved in the dev-environment, but to fix the desert problem, I have to do some more learnings about datapack world generator customizations.
