### ISSUE TITLE
Carrier Mod Issues

### ISSUE THREAD

**Issue by KonSola5** [MSandro/sky_fabrication3#73]
The Carrier mod is nice in early game for transporting chests, but later in game it becomes quickly a nuisance.
Most notable problems are:

- Picking up MI Machines - this causes EU cables to disconnect, which is quite an annoyance.
- Picking up AE2 Cable and/or Bus: this can lead to accidental disconnects, which in large network means the network will take a bit of time to reboot. Also, this prevents locking the ME Storage Monitors (which uses Shift-Right Click).
- Picking up Cardboard Boxes from Coxinha Utilities - it prevents you from unpacking a block.
- Picking up Mob Spatial Harvesters causes the game to crash upon placing the harvester down.

A solution would be to set the Carrier config to **whitelist** instead of **blacklist**.

Also, why Expanded Storage is on the blacklist?

**Comment by ivanpu** [comment]
Tip: you can rebind the "Carrier key" from Shift to any other button.
This solved most of the issues with this mod for me (consistently remembering that I've changed this keybind is still a unresolved issue for now).

**Comment by KonSola5** [comment]
Thanks for the tip! Completely missed that you can rebind carrying!

**Comment by MSandro** [comment]
> Also, why Expanded Storage is on the blacklist?

It caused a dupe glitch

**Comment by KonSola5** [comment]
Ok, that makes sense.

**Comment by KonSola5** [comment]
Reopening, because there is another problem regarding the Carrier mod:
With the Carrier Mod installed, you can't spin Hand Cranks clockwise with Shift-Right Click, unless you have an item in hand (because carrying action is prioritized, even if blacklisted), also unless you rebind the carrying key to something else than Left Shift.

When you have an item in hand, you can't spin Hand Cranks clockwise continuously (even with the Carrier keybind changed!).

This also applies to Analog Levers.
Issue here: [https://github.com/GabrielOlvH/Carrier/issues/58](https://github.com/GabrielOlvH/Carrier/issues/58)

**Comment by MSandro** [comment]
ExpandedStorage Blocks will be able to be carried in 0.6.0 again.
