### ISSUE TITLE
Emergency Bamboo

### ISSUE THREAD

**Issue by StormOfGalaxy** [MSandro/sky_fabrication3#76]
If you accidentally destroy the last bamboo, Ann you can not continue playing the game without cheating. In FTBQuest there should be a possibility to give emergency items.

**Comment by KonSola5** [comment]
This would be a bit tricky to implement, since you can choose 3 different early-game paths and only one set of emergency items.

**Comment by KonSola5** [comment]
As I said about trickiness: I implemented emergency items by creating a custom `/emergency` command using KubeJS. Now as a part of a "proposed changes" pull request!
Gives different items depending of chosen island:

- Oak Sapling for the Tree Island,
- Bamboo for the Bamboo Island,
- Fishing Rod for the Fishing Island.

There is a 5 minute cooldown before using the command again.

![cmd](https://user-images.githubusercontent.com/125081901/220204971-3dfe3a6a-7bd1-4039-a2e9-b28ff6602865.png)

Learnt about regex matching along the way.

**Comment by MSandro** [comment]
will be solved in SF3 v0.6.0 which will be released soon.
many thanks again @KonSola5 for your great help.
