### ISSUE TITLE
[Suggestion] A mod that fixes interaction between Hephaestus and FTB Ultimine

### ISSUE THREAD

**Issue by KonSola5** [MSandro/sky_fabrication3#77]
The mod in question:
[https://www.curseforge.com/minecraft/mc-mods/tamago](https://www.curseforge.com/minecraft/mc-mods/tamago)

**Comment by MSandro** [comment]
thanks for the suggestion, I will try it out, and if I works like expected I'll add it in SF3 v0.6.0.
