### ISSUE TITLE
error when interact with slab

### ISSUE THREAD

**Issue by juanretamales** [MSandro/sky_fabrication3#8]
Version: 0.3c

when a cobblestone slab place over a wooden slab. 
and the last is when sand fall into wooden slab (with this my save is now corrupt)

https://crashy.net/bDk2P53SFg8kXC0cqFGy

the backup is corrupt then with amulet editor remove the corrupts blocks

**Comment by MSandro** [comment]
known bug, I hope for an answer of the mod dev soon:
https://github.com/CebbysMods/refabslab-mod/issues/22

**Comment by MSandro** [comment]
mod will be updated to version 0.7.4 to fix this issue soon.
