### ISSUE TITLE
End(Void) is broken for the dragon 

### ISSUE THREAD

**Issue by Florianfifteen** [MSandro/sky_fabrication3#81]
The server crashed after I suffered from breathering Dragon
![image](https://user-images.githubusercontent.com/70654082/225709856-d7cad20e-54c1-4b0f-a4cc-d66d3c141dad.png)
My server crash already and I need to restart

**Comment by MSandro** [comment]
I've tried to reproduce it in the 0.6.0 dev version, there I am not able to cause a crash while fighting agains the dragon.
Maybe a mod update solved it, or the removing of ProgressiveBosses solved this issue as well.
