### ISSUE TITLE
Quest items issues

### ISSUE THREAD

**Issue by ivanpu** [MSandro/sky_fabrication3#82]
_After getting a bit too many "Missing Items" as a rewards..._

There are items from missing mods in the quests. Some are fixable, some probably should be removed.

Rewards:
`@terrarianslimes` - missing mod - 5 items
`waystones:waystone` - wrong mod - should be `fwaystones:waystone` (missing leading **f**)

In the quest book:
* "Building"
   - final reward - missing mod - you probably want `wands:creative_wand`?
* "Tools and Armor"
   - Infusion table - missing mod
   - Machetes, Scythes - broken filter (missing mods?)
   - Jetpacks - missing item `iron-jetpack:obamium_jetpack`
* "Adventurer"
   - Observation - wrong waystone mod (as in the rewards)
* "Challenges"
   - Boss Rush - terrarian king slime

**Comment by KonSola5** [comment]
All of these will be fixed in 0.6.0.

Challenges are hidden (carryover from AOF5), so they weren't touched.

**Comment by Jlomaka** [comment]
Same problem with salt, fabricaeexnihilo:salt_bottle you can't obtain it or craft. Quest Salt and Brine.

**Comment by KonSola5** [comment]
Will need to investigate that.

Edit: Just use a Glass Bottle on a Sand Block. It's even in the quest description.

![salt](https://user-images.githubusercontent.com/125081901/226683348-cf6f2cf7-f660-4725-ade6-dd7be7d70aa1.png)
