### ISSUE TITLE
Fishing Rewards

### ISSUE THREAD

**Issue by Qharre** [MSandro/sky_fabrication3#83]
There's a chance of just nothing being given to you upon fishing.

**Comment by KonSola5** [comment]
Finally found, why:
![bug](https://user-images.githubusercontent.com/125081901/232135788-0a91690f-d4cd-45b7-9bda-18daa9aa0a31.png)
I think what's happening is you rolled an item, that doesn't exist in this pack.
Obviously this will be yeeted.
