### ISSUE TITLE
Straw not dropping?

### ISSUE THREAD

**Issue by Mystil** [MSandro/sky_fabrication3#85]
Straw is supposed to drop from Grass, Tall Grass, Wheat Seeds, and Rice. My friend and I have not gotten a single Straw from Grass, Tall Grass, or Wheat Seeds.

![image](https://user-images.githubusercontent.com/1700954/230659331-611060a3-bdb7-433f-a0ff-517a5904df9f.png)
![image](https://user-images.githubusercontent.com/1700954/230659522-ad13b06a-0e7e-4a04-acb8-fbeaf97ed267.png)
![image](https://user-images.githubusercontent.com/1700954/230659580-682259d8-10ed-4514-93d4-694ee0eced35.png)
![image](https://user-images.githubusercontent.com/1700954/230659979-f0fd6bc5-630a-47b1-9e5a-6186d63b134d.png)

**Comment by Mystil** [comment]
![image](https://user-images.githubusercontent.com/1700954/230660722-56c43df4-d568-46fd-8a90-e5edd9fc03b4.png)

**Comment by KonSola5** [comment]
Break Grass using Farmer's Delight knives to get Straw.
