### ISSUE TITLE
Create Brass doenst count as Tech Reborn Brass, yet still is craftable in the Alloy Forge

### ISSUE THREAD

**Issue by openblocki** [MSandro/sky_fabrication3#87]
Create Brass doenst count as Tech Reborn Brass, yet still is craftable in the Alloy Forge

Solution is either adding some OreDict Tag or Material Tag, or changing the Recipe, so it gives the right brass

**Comment by KonSola5** [comment]
Fixed in the future update
![brass](https://user-images.githubusercontent.com/125081901/231259777-330062ba-c7ae-4609-a690-1345feb175c8.png)
The problem was in priority of outputs: Create's Brass had a higher priority than Tech Reborn Brass.

**Comment by KonSola5** [comment]
An addendum: Minecraft above 1.13 has tags (item/block/entity tags), which are pretty much a more powerful version of Ore Dictionary, they're also right in vanilla!
