### ISSUE TITLE
Quest book doesnt Recognize Diamond Mesh

### ISSUE THREAD

**Issue by openblocki** [MSandro/sky_fabrication3#88]
Nothing more to say.
Could be because of left over NBT Data from Create crafting Recipe
Edit: Item needs to be moved inside inventory so the quest book recognizes it

**Comment by KonSola5** [comment]
Sometimes this can also happen when you craft in the Hephaestus' Crafting Station.

But this is from Create's Sequenced Assembly, so it should be fine.

But yeah - updating the inventory in any way will trigger the quest.
