### ISSUE TITLE
Bamboo leaves don't voidcraft

### ISSUE THREAD

**Issue by Trogdayton** [MSandro/sky_fabrication3#9]
Decided the second time around I wanted to do the bamboo island, but even though I'm crouching on a slab and throwing bamboo thatch into the void it's not giving me leaves. Am I simply misunderstanding it or is it a bug? I don't know what info you need, let me know. I'm on the 0.3c hotfix. Can't guarantee it's the hotfix that did it, since I haven't done the bamboo island before this. Oak island worked fine.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/181172321-459a86c0-c17a-4bed-8d99-fe1e6d69fb63.png)
https://user-images.githubusercontent.com/10937159/181172997-0d2dc796-5214-4f4f-aa0d-dd41ec560a3a.mp4

it works but the recipe has a loss rate.

**Comment by Trogdayton** [comment]
Sorry, I guess I just have incredibly bad RNG. I've tossed more than half a
stack, and no leaves yet. Do they come down from above, or back up from the
void? I've never actually used a void craft recipe before.

**Comment by MSandro** [comment]
take a look at this video:
https://user-images.githubusercontent.com/10937159/181172997-0d2dc796-5214-4f4f-aa0d-dd41ec560a3a.mp4
right near you

**Comment by Trogdayton** [comment]
Thanks!
