### ISSUE TITLE
0.6.0 crash when loading any world

### ISSUE THREAD

**Issue by ivanpu** [MSandro/sky_fabrication3#93]
Couldn't open any world after update, either new or existing - the game crashes every time.
After reading about profiler in the crash log - I've disabled the "spark" mod, and it loads worlds fine now.

**Comment by MSandro** [comment]
Thanks, could you please provide some logs, so I could forward it to the developers of Spark.

**Comment by ivanpu** [comment]
Fixed by updating java - apparently I had a bit old version.
