### ISSUE TITLE
server version 0.6.0 is not working 

### ISSUE THREAD

**Issue by SireTeddy** [MSandro/sky_fabrication3#97]
hello dear MSandro,
I installed 0.6.0 of SF3, on my server, and i can't start it, i have an issue with mods compatibility with fabric version.
I think server pack don't have the necessary fabric API updates, and not all the mods updates necessary for working.
Cordially, Teddy

that is my pastebin for lastest logs : https://pastebin.com/r1ZticvB

**Comment by MSandro** [comment]
You are running a older Fabric Loader Version

**Comment by SireTeddy** [comment]
Yes i know, but when i install a pack, they already have the fabric version, so i think they don't have the correct version of fabric on the server pack

**Comment by MSandro** [comment]
In the server Zip I have included Version 0.14.19
Are u using any mc server hosting provider? Maybe u have to configure the fabric version there in the web ui.

**Comment by SireTeddy** [comment]
I use pterodactyl panel, and an addon to auto install modpackq from curseforge. On the past i had any problems for fabric or fprge version

**Comment by MSandro** [comment]
Download the fabric loader from here: https://meta.fabricmc.net/v2/versions/loader/1.18.2/0.14.19/0.11.2/server/jar
Name the file correctly to match your panels configuration, and upload the file to your server

**Comment by MSandro** [comment]
the 0.6.0 Server File contains a file named fabric-server-launch.jar (version 0.14.19)
